console.warn("*********************************************************************************************************");
console.warn("*                                                                                                       *");
console.warn("*                                     IMPORTANT COPYRIGHT NOTICE AND WARNING                            *");
console.warn("*                                                                                                       *");
console.warn("*   You are about to use a script that is copyrighted and protected by international copyright laws and  *");
console.warn("*   treaties. This script, including all of its contents, structure, design, and functionality, is the   *");
console.warn("*   exclusive property of its author. Any unauthorized use, copying, distribution, modification, or      *");
console.warn("*   reproduction of this script, in whole or in part, is strictly prohibited and subject to severe civil *");
console.warn("*   and criminal penalties. Unauthorized use of this script will be prosecuted to the fullest extent     *");
console.warn("*   possible under the law. If you have not been authorized by the author to use this script, please     *");
console.warn("*   delete it immediately and report any incidents of unauthorized access or use to the author at        *");
console.warn("*   https://github.com/ejjays.                                                                           *");
console.warn("*                                                                                                       *");
console.warn("*   This script is intended for the exclusive use of its authorized users. Unauthorized access,          *");
console.warn("*   duplication, dissemination, or exploitation of this script and its components is strictly forbidden. *");
console.warn("*   Violators will face legal consequences, including but not limited to lawsuits, financial penalties,  *");
console.warn("*   and criminal charges. Any attempt to reverse engineer, decompile, disassemble, or otherwise extract  *");
console.warn("*   the source code, algorithms, or trade secrets contained within this script is expressly prohibited.  *");
console.warn("*                                                                                                       *");
console.warn("*   The author reserves all rights not expressly granted herein. By continuing to use this script, you   *");
console.warn("*   acknowledge that you have read this notice, understand its terms, and agree to comply with all       *");
console.warn("*   copyright laws and the terms of use set forth herein. Failure to comply with these terms will result *");
console.warn("*   in appropriate legal action, including but not limited to immediate termination of your rights to    *");
console.warn("*   use this script and liability for damages.                                                          *");
console.warn("*                                                                                                       *");
console.warn("*   If you are in doubt about whether you have been granted permission to use this script, or if you     *");
console.warn("*   have any questions regarding your rights and obligations under this copyright notice, please contact *");
console.warn("*   the author immediately at https://github.com/ejjays for clarification.                              *");
console.warn("*                                                                                                       *");
console.warn("*   COPYRIGHT © 2024 ejjays. All rights reserved. Unauthorized use, reproduction, or distribution of     *");
console.warn("*   this script, or any portion thereof, is strictly prohibited and will be prosecuted to the fullest    *");
console.warn("*   extent of the law.                                                                                   *");
console.warn("*                                                                                                       *");
console.warn("*   Unauthorized use, access, or distribution of this script may also result in immediate revocation of  *");
console.warn("*   your rights to use this script, as well as additional damages and penalties to be determined by the  *");
console.warn("*   courts. The author of this script takes the protection of intellectual property very seriously and   *");
console.warn("*   will take all necessary steps to safeguard these rights.                                             *");
console.warn("*                                                                                                       *");
console.warn("*   By using this script, you agree to indemnify and hold the author harmless from any and all claims,   *");
console.warn("*   damages, liabilities, costs, and expenses, including but not limited to attorney's fees, arising     *");
console.warn("*   from or related to your use of the script in violation of this copyright notice. You also agree to   *");
console.warn("*   cooperate with the author in any investigations or legal actions taken to enforce these rights.      *");
console.warn("*                                                                                                       *");
console.warn("*   Please be aware that any violation of this copyright notice will be regarded as a serious offense    *");
console.warn("*   and will be pursued vigorously to the fullest extent allowed by law. The author reserves the right   *");
console.warn("*   to update and modify this copyright notice at any time without prior notice. It is your              *");
console.warn("*   responsibility to ensure that you are in compliance with the most current version of this notice.    *");
console.warn("*                                                                                                       *");
console.warn("*   The author appreciates your understanding and cooperation in protecting intellectual property rights.*");
console.warn("*   Thank you for respecting the hard work and creativity that goes into developing and maintaining this *");
console.warn("*   script.                                                                                             *");
console.warn("*                                                                                                       *");
console.warn("*   This copyright notice serves as a legal agreement between the user and the author. By using this     *");
console.warn("*   script, you agree to be bound by the terms and conditions outlined in this notice. Any breach of     *");
console.warn("*   these terms will result in immediate termination of your rights to use the script and may result in  *");
console.warn("*   further legal action.                                                                               *");
console.warn("*                                                                                                       *");
console.warn("*   The author reserves the right to monitor the use of this script to ensure compliance with this       *");
console.warn("*   copyright notice. Any unauthorized attempts to access or use this script, or to bypass any security  *");
console.warn("*   measures in place, will be detected and logged.                                                      *");
console.warn("*                                                                                                       *");
console.warn("*   The author also reserves the right to seek injunctive relief in addition to any other remedies       *");
console.warn("*   available at law or in equity, in order to protect their intellectual property rights. Any failure   *");
console.warn("*   by the author to enforce any part of this copyright notice shall not be deemed a waiver of the       *");
console.warn("*   author's rights to enforce this notice at a later date.                                              *");
console.warn("*                                                                                                       *");
console.warn("*   This copyright notice shall be governed by and construed in accordance with the laws of the          *");
console.warn("*   jurisdiction in which the author resides, without regard to its conflicts of law principles.         *");
console.warn("*   Any legal actions or proceedings arising out of or related to this copyright notice shall be         *");
console.warn("*   brought exclusively in the courts of the jurisdiction in which the author resides.                   *");
console.warn("*                                                                                                       *");
console.warn("*   If any provision of this copyright notice is found to be invalid or unenforceable by a court of      *");
console.warn("*   competent jurisdiction, such provision shall be deemed severed from the notice and the remaining     *");
console.warn("*   provisions shall remain in full force and effect.                                                    *");
console.warn("*                                                                                                       *");
console.warn("*   The headings in this copyright notice are for convenience only and shall not affect the              *");
console.warn("*   interpretation of any terms.                                                                        *");
console.warn("*                                                                                                       *");
console.warn("*   This copyright notice constitutes the entire agreement between the user and the author regarding     *");
console.warn("*   the use of this script and supersedes all prior or contemporaneous communications and proposals,     *");
console.warn("*   whether oral, written, or electronic, between the user and the author with respect to this script.   *");
console.warn("*                                                                                                       *");
console.warn("*   The author of this script is committed to ensuring the protection and confidentiality of any         *");
console.warn("*   personal information that may be collected in connection with the use of this script. Any such       *");
console.warn("*   information will be handled in accordance with applicable privacy laws and the author's privacy      *");
console.warn("*   policy, which is available upon request.                                                            *");
console.warn("*                                                                                                       *");
console.warn("*   For any questions, concerns, or requests related to this copyright notice or the use of this script, *");
console.warn("*   please contact the author at https://github.com/ejjays. The author is committed to addressing any    *");
console.warn("*   issues promptly and thoroughly to ensure the best possible experience for authorized users of this   *");
console.warn("*   script.                                                                                             *");
console.warn("*                                                                                                       *");
console.warn("*********************************************************************************************************");

(function() {
    var js, fs, d = document, id = "tars-widget-script", b = "https://tars-file-upload.s3.amazonaws.com/bulb/";
    if (!d.getElementById(id)) {
        js = d.createElement("script");
        js.id = id;
        js.type = "text/javascript";
        js.src = b + "js/widget.js";
        fs = d.getElementsByTagName("script")[0];
        fs.parentNode.insertBefore(js, fs);
    }
})();

window.tarsSettings = {"convid": "25E8bl"};
